# Generated by Django 3.0.6 on 2020-05-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test',
            field=models.CharField(default='on', max_length=200),
            preserve_default=False,
        ),
    ]
